name:
  ok
github:
  hlian/advent
dependencies:
  - base
  - base-prelude
  - containers
  - MissingH
  - split
  - text
  - bytestring
  - megaparsec
  - regex-compat
  - pqueue
  - lens
  - hashable
  - unordered-containers
  - vector
default-extensions:
  - OverloadedStrings
ghc-options:
  -O2
executables:
  d13:
    main: Main.hs
    source-dirs: src/2016/
