name:
  ok
github:
  hlian/advent
dependencies:
  - base
  - base-prelude
  - containers
default-extensions:
  - OverloadedStrings
ghc-options:
  -O2
executables:
  d13:
    main: Main.hs
    source-dirs: src/2016/
